from random import randrange
#from random import shuffle
#import numpy as np

#RAND_MAX = 2147483647

RAND_MAX = 1023 * 1023 * 1023

def shuffle(lst):
    for i in range(len(lst)):
        j = i + int(randrange(RAND_MAX + 1) / (RAND_MAX / (len(lst) - i) + 1))
        t = lst[j]
        lst[j] = lst[i]
        lst[i] = t


def generate2(width=31, height=31):
    if width < 5:
        raise Exception('Maze width must be >= 5')

    if width % 2 == 0:
        raise Exception('Maze weight must be odd')

    if height < 5:
        raise Exception('Maze height must be >= 5')

    if height % 2 == 0:
        raise Exception('Maze height must be odd')

    grid = [ [ True ] * width ] * height
    #return width, height, grid
    ##grid = np.full((height, width), True, dtype=bool)

    forest = []
    for row in range(1, height - 1, 2):
        for col in range(1, width - 1, 2):
            forest.append([(row, col)])
            grid[row][col] = False

    edges = []
    for row in range(2, height - 1, 2):
        for col in range(1, width - 1, 2):
            edges.append((row, col))

    for row in range(1, height - 1, 2):
        for col in range(2, width - 1, 2):
            edges.append((row, col))

    shuffle(edges)

    while len(forest) > 1:
        ce_row, ce_col = edges[0]
        edges = edges[1:]

        tree1 = -1
        tree2 = -1

        if ce_row % 2 == 0:  # even-numbered row: vertical wall
            tree1 = sum([
                i if (ce_row - 1, ce_col) in j else 0
                for i, j in enumerate(forest)
            ])
            tree2 = sum([
                i if (ce_row + 1, ce_col) in j else 0
                for i, j in enumerate(forest)
            ])
        else:  # odd-numbered row: horizontal wall
            tree1 = sum([
                i if (ce_row, ce_col - 1) in j else 0
                for i, j in enumerate(forest)
            ])
            tree2 = sum([
                i if (ce_row, ce_col + 1) in j else 0
                for i, j in enumerate(forest)
            ])

        if tree1 != tree2:
            new_tree = forest[tree1] + forest[tree2]
            temp1 = list(forest[tree1])
            temp2 = list(forest[tree2])
            forest = [x for x in forest if x != temp1]
            forest = [x for x in forest if x != temp2]
            forest.append(new_tree)
            grid[ce_row][ce_col] = False

    return width, height, grid


def generate():
    # maze = [[ True,  True,  True,  True,  True,  True,  True],
    #     [ True, False,  True, False,  True, False,  True],
    #     [ True, False,  True, False,  True, False,  True],
    #     [ True, False, False, False,  True, False,  True],
    #     [ True, False,  True, False,  True, False,  True],
    #     [ True, False,  True, False, False, False,  True],
    #     [ True,  True,  True,  True,  True,  True,  True]]
    maze1 = [[ True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True],
        [ True, False, False, False,  True, False, False, False, False,
            False, False, False,  True, False,  True, False, False, False,
            True, False, False, False, False, False,  True, False, False,
            False,  True, False,  True],
        [ True, False,  True, False,  True,  True,  True,  True,  True,
            True,  True, False,  True, False,  True,  True,  True, False,
            True, False,  True,  True,  True, False,  True,  True,  True,
            False,  True, False,  True],
        [ True, False,  True, False, False, False, False, False, False,
            False, False, False, False, False,  True, False, False, False,
            False, False,  True, False, False, False,  True, False,  True,
            False, False, False,  True],
        [ True,  True,  True,  True,  True,  True,  True, False,  True,
            True,  True,  True,  True, False,  True, False,  True, False,
            True,  True,  True,  True,  True,  True,  True, False,  True,
            False,  True,  True,  True],
        [ True, False, False, False, False, False, False, False, False,
            False,  True, False, False, False,  True, False,  True, False,
            False, False, False, False, False, False, False, False,  True,
            False,  True, False,  True],
        [ True,  True,  True,  True,  True, False,  True,  True,  True,
            True,  True, False,  True,  True,  True,  True,  True,  True,
            True,  True,  True, False,  True, False,  True,  True,  True,
            False,  True, False,  True],
        [ True, False, False, False, False, False, False, False,  True,
            False,  True, False,  True, False, False, False, False, False,
            False, False,  True, False,  True, False, False, False, False,
            False, False, False,  True],
        [ True,  True,  True, False,  True, False,  True,  True,  True,
            False,  True,  True,  True,  True,  True, False,  True,  True,
            True,  True,  True,  True,  True, False,  True,  True,  True,
            True,  True,  True,  True],
        [ True, False, False, False,  True, False, False, False,  True,
            False, False, False,  True, False, False, False, False, False,
            False, False, False, False, False, False,  True, False, False,
            False,  True, False,  True],
        [ True,  True,  True, False,  True,  True,  True,  True,  True,
            False,  True,  True,  True, False,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            False,  True, False,  True],
        [ True, False,  True, False, False, False, False, False,  True,
            False, False, False, False, False, False, False,  True, False,
            True, False, False, False, False, False, False, False, False,
            False, False, False,  True],
        [ True, False,  True,  True,  True, False,  True,  True,  True,
            False,  True,  True,  True, False,  True,  True,  True, False,
            True,  True,  True,  True,  True, False,  True,  True,  True,
            False,  True,  True,  True],
        [ True, False, False, False, False, False,  True, False, False,
            False,  True, False,  True, False, False, False, False, False,
            True, False, False, False,  True, False,  True, False, False,
            False, False, False,  True],
        [ True,  True,  True,  True,  True, False,  True, False,  True,
            True,  True, False,  True, False,  True,  True,  True,  True,
            True, False,  True, False,  True, False,  True,  True,  True,
            False,  True,  True,  True],
        [ True, False,  True, False, False, False, False, False,  True,
            False, False, False,  True, False, False, False, False, False,
            False, False,  True, False, False, False,  True, False,  True,
            False, False, False,  True],
        [ True, False,  True,  True,  True,  True,  True,  True,  True,
            True,  True, False,  True, False,  True, False,  True,  True,
            True, False,  True,  True,  True, False,  True, False,  True,
            True,  True,  True,  True],
        [ True, False,  True, False, False, False, False, False,  True,
            False,  True, False, False, False,  True, False,  True, False,
            False, False,  True, False, False, False, False, False, False,
            False, False, False,  True],
        [ True, False,  True, False,  True, False,  True, False,  True,
            False,  True,  True,  True, False,  True, False,  True, False,
            True,  True,  True,  True,  True, False,  True, False,  True,
            True,  True, False,  True],
        [ True, False, False, False,  True, False,  True, False, False,
            False, False, False, False, False,  True, False,  True, False,
            True, False, False, False,  True, False,  True, False, False,
            False,  True, False,  True],
        [ True,  True,  True, False,  True,  True,  True, False,  True,
            True,  True, False,  True, False,  True,  True,  True,  True,
            True,  True,  True, False,  True,  True,  True,  True,  True,
            False,  True, False,  True],
        [ True, False, False, False, False, False,  True, False,  True,
            False, False, False,  True, False,  True, False, False, False,
            True, False, False, False,  True, False, False, False, False,
            False,  True, False,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
            False,  True,  True,  True,  True,  True, False,  True,  True,
            True,  True,  True, False,  True, False,  True,  True,  True,
            False,  True,  True,  True],
        [ True, False,  True, False,  True, False, False, False, False,
            False, False, False,  True, False, False, False, False, False,
            False, False, False, False, False, False,  True, False, False,
            False,  True, False,  True],
        [ True, False,  True, False,  True, False,  True, False,  True,
            True,  True, False,  True, False,  True,  True,  True,  True,
            True, False,  True, False,  True,  True,  True,  True,  True,
            True,  True, False,  True],
        [ True, False,  True, False, False, False,  True, False,  True,
            False, False, False,  True, False,  True, False, False, False,
            False, False,  True, False, False, False, False, False, False,
            False, False, False,  True],
        [ True, False,  True, False,  True,  True,  True, False,  True,
            True,  True, False,  True, False,  True,  True,  True, False,
            True, False,  True,  True,  True,  True,  True, False,  True,
            False,  True,  True,  True],
        [ True, False, False, False, False, False,  True, False,  True,
            False, False, False,  True, False, False, False,  True, False,
            True, False, False, False,  True, False,  True, False,  True,
            False, False, False,  True],
        [ True, False,  True,  True,  True, False,  True,  True,  True,
            False,  True,  True,  True,  True,  True,  True,  True, False,
            True, False,  True,  True,  True, False,  True,  True,  True,
            False,  True, False,  True],
        [ True, False,  True, False, False, False, False, False,  True,
            False, False, False, False, False,  True, False, False, False,
            True, False, False, False,  True, False, False, False, False,
            False,  True, False,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True]]

    maze2 = [[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False, False, False,
        False, False, False,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
        False,  True, False,  True,  True,  True, False,  True,  True,
         True, False,  True, False,  True,  True,  True,  True,  True,
         True,  True, False,  True],
       [ True, False, False, False, False, False,  True, False, False,
        False,  True, False,  True, False, False, False, False, False,
         True, False,  True, False,  True, False, False, False,  True,
        False,  True, False,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True, False,  True, False,  True,  True,  True,
        False,  True, False,  True],
       [ True, False, False, False, False, False, False, False,  True,
        False, False, False, False, False,  True, False, False, False,
         True, False,  True, False, False, False, False, False,  True,
        False, False, False,  True],
       [ True, False,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True],
       [ True, False,  True, False,  True, False, False, False,  True,
        False,  True, False,  True, False, False, False,  True, False,
        False, False, False, False, False, False, False, False,  True,
        False, False, False,  True],
       [ True,  True,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True, False,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True],
       [ True, False, False, False, False, False,  True, False,  True,
        False, False, False,  True, False, False, False, False, False,
         True, False, False, False,  True, False, False, False,  True,
        False,  True, False,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True],
       [ True, False, False, False, False, False, False, False, False,
        False, False, False,  True, False,  True, False,  True, False,
         True, False, False, False, False, False, False, False, False,
        False, False, False,  True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True, False,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True, False,  True],
       [ True, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True, False,
        False, False,  True, False, False, False,  True, False, False,
        False,  True, False,  True],
       [ True,  True,  True,  True,  True,  True,  True, False,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True, False,  True,  True,  True, False,  True,
         True,  True,  True,  True],
       [ True, False,  True, False, False, False,  True, False, False,
        False,  True, False, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False,
        False,  True, False,  True],
       [ True, False,  True, False,  True,  True,  True, False,  True,
         True,  True, False,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True, False,  True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True, False,  True, False,  True, False,
         True, False, False, False, False, False, False, False, False,
        False,  True, False,  True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True, False,  True, False,  True,  True,  True,  True,  True,
         True,  True, False,  True],
       [ True, False, False, False, False, False, False, False,  True,
        False,  True, False,  True, False, False, False, False, False,
        False, False,  True, False, False, False,  True, False,  True,
        False,  True, False,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True, False,  True, False,  True, False,  True,  True,
         True,  True,  True, False,  True,  True,  True, False,  True,
        False,  True, False,  True],
       [ True, False,  True, False,  True, False,  True, False, False,
        False,  True, False, False, False,  True, False, False, False,
         True, False, False, False, False, False, False, False,  True,
        False,  True, False,  True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True, False,  True],
       [ True, False, False, False,  True, False, False, False,  True,
        False,  True, False, False, False,  True, False, False, False,
         True, False, False, False,  True, False, False, False, False,
        False,  True, False,  True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True,  True,  True,  True,  True, False,
         True,  True,  True, False,  True,  True,  True,  True,  True,
        False,  True, False,  True],
       [ True, False,  True, False, False, False,  True, False,  True,
        False,  True, False, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False,
        False, False, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True,
         True,  True, False,  True, False,  True,  True,  True,  True,
         True, False,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True, False,  True, False, False, False, False, False,  True,
        False, False, False,  True, False, False, False,  True, False,
         True, False,  True, False, False, False, False, False, False,
        False, False, False,  True],
       [ True, False,  True,  True,  True, False,  True, False,  True,
        False,  True,  True,  True, False,  True,  True,  True, False,
         True, False,  True, False,  True,  True,  True,  True,  True,
         True,  True, False,  True],
       [ True, False,  True, False, False, False,  True, False, False,
        False,  True, False, False, False, False, False,  True, False,
        False, False,  True, False, False, False, False, False,  True,
        False, False, False,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True]]

    maze3 = [[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True, False, False, False, False, False, False, False,  True,
        False, False, False,  True, False,  True, False, False, False,
        False, False,  True, False, False, False,  True, False,  True,
        False,  True, False,  True],
       [ True, False,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True, False,  True, False,  True, False,
         True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True],
       [ True, False,  True, False, False, False,  True, False,  True,
        False, False, False,  True, False, False, False,  True, False,
         True, False, False, False,  True, False, False, False,  True,
        False,  True, False,  True],
       [ True,  True,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True, False,  True],
       [ True, False, False, False,  True, False, False, False, False,
        False,  True, False, False, False, False, False,  True, False,
         True, False, False, False, False, False,  True, False, False,
        False, False, False,  True],
       [ True,  True,  True, False,  True,  True,  True, False,  True,
         True,  True, False,  True,  True,  True,  True,  True, False,
         True,  True,  True, False,  True,  True,  True, False,  True,
         True,  True,  True,  True],
       [ True, False,  True, False, False, False,  True, False,  True,
        False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False,  True, False, False,
        False, False, False,  True],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True, False,  True,  True,  True,
        False,  True, False,  True],
       [ True, False, False, False,  True, False,  True, False, False,
        False, False, False,  True, False,  True, False,  True, False,
        False, False, False, False,  True, False,  True, False, False,
        False,  True, False,  True],
       [ True, False,  True, False,  True, False,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True, False,  True],
       [ True, False,  True, False, False, False, False, False,  True,
        False, False, False, False, False,  True, False, False, False,
        False, False,  True, False, False, False,  True, False, False,
        False,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True, False,
         True, False,  True,  True,  True, False,  True,  True,  True,
        False,  True, False,  True],
       [ True, False, False, False, False, False,  True, False,  True,
        False, False, False, False, False, False, False, False, False,
         True, False, False, False, False, False,  True, False,  True,
        False,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False,  True, False,  True, False,
         True, False,  True,  True,  True,  True,  True, False,  True,
        False,  True,  True,  True],
       [ True, False, False, False,  True, False,  True, False, False,
        False, False, False, False, False,  True, False,  True, False,
         True, False,  True, False, False, False, False, False, False,
        False,  True, False,  True],
       [ True,  True,  True, False,  True, False,  True, False,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True, False,  True,
        False,  True, False,  True],
       [ True, False, False, False,  True, False, False, False,  True,
        False,  True, False, False, False, False, False,  True, False,
        False, False, False, False,  True, False,  True, False,  True,
        False,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True],
       [ True, False,  True, False, False, False, False, False,  True,
        False, False, False, False, False,  True, False,  True, False,
        False, False,  True, False,  True, False, False, False,  True,
        False, False, False,  True],
       [ True, False,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True, False,  True, False,  True,  True,  True,
        False,  True, False,  True],
       [ True, False, False, False, False, False,  True, False, False,
        False, False, False, False, False, False, False,  True, False,
         True, False, False, False,  True, False, False, False,  True,
        False,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False,  True, False,  True, False,
         True,  True,  True, False,  True,  True,  True, False,  True,
         True,  True,  True,  True],
       [ True, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False,  True, False,  True, False,
         True, False, False, False,  True, False, False, False, False,
        False, False, False,  True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True, False,  True,  True,  True, False,  True,
         True,  True, False,  True],
       [ True, False,  True, False, False, False, False, False, False,
        False,  True, False,  True, False,  True, False, False, False,
        False, False,  True, False, False, False, False, False, False,
        False,  True, False,  True],
       [ True, False,  True, False,  True, False,  True, False,  True,
         True,  True, False,  True, False,  True, False,  True,  True,
         True,  True,  True, False,  True,  True,  True, False,  True,
        False,  True,  True,  True],
       [ True, False, False, False,  True, False,  True, False, False,
        False, False, False,  True, False, False, False, False, False,
         True, False, False, False, False, False,  True, False,  True,
        False,  True, False,  True],
       [ True, False,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True, False,  True,  True,  True,  True,  True, False,  True,
         True,  True, False,  True],
       [ True, False,  True, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
         True, False, False, False,  True, False, False, False, False,
        False, False, False,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True]]

    maze4 = [[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True, False, False, False, False, False, False, False,  True,
        False, False, False,  True, False,  True, False, False, False,
        False, False, False, False,  True, False,  True, False, False,
        False,  True, False,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True, False,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True, False,  True],
       [ True, False, False, False, False, False, False, False,  True,
        False, False, False, False, False,  True, False,  True, False,
         True, False, False, False, False, False,  True, False, False,
        False, False, False,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True, False,  True,  True,  True, False,  True, False,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True, False,  True],
       [ True, False,  True, False, False, False,  True, False, False,
        False, False, False,  True, False,  True, False,  True, False,
        False, False,  True, False, False, False,  True, False, False,
        False, False, False,  True],
       [ True, False,  True, False,  True, False,  True,  True,  True,
         True,  True,  True,  True, False,  True, False,  True,  True,
         True, False,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True],
       [ True, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False,
        False, False, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True,
         True,  True, False,  True, False,  True, False,  True,  True,
         True,  True,  True, False,  True, False,  True,  True,  True,
         True,  True, False,  True],
       [ True, False, False, False,  True, False,  True, False,  True,
        False, False, False,  True, False,  True, False, False, False,
        False, False, False, False,  True, False,  True, False, False,
        False,  True, False,  True],
       [ True, False,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True, False,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
        False,  True, False,  True],
       [ True, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False,  True, False, False, False,
        False, False,  True, False, False, False,  True, False,  True,
        False,  True, False,  True],
       [ True,  True,  True, False,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True,
         True, False,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True,  True],
       [ True, False,  True, False, False, False, False, False, False,
        False,  True, False, False, False,  True, False,  True, False,
        False, False, False, False,  True, False,  True, False,  True,
        False, False, False,  True],
       [ True, False,  True, False,  True, False,  True,  True,  True,
        False,  True, False,  True, False,  True,  True,  True,  True,
         True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True],
       [ True, False, False, False,  True, False,  True, False,  True,
        False, False, False,  True, False,  True, False, False, False,
        False, False,  True, False,  True, False, False, False, False,
        False,  True, False,  True],
       [ True, False,  True,  True,  True, False,  True, False,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True],
       [ True, False, False, False,  True, False,  True, False, False,
        False,  True, False, False, False, False, False,  True, False,
         True, False, False, False, False, False,  True, False, False,
        False,  True, False,  True],
       [ True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True, False,  True, False,  True,  True,  True,
         True,  True, False,  True],
       [ True, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False, False, False,
        False, False,  True, False,  True, False,  True, False,  True,
        False, False, False,  True],
       [ True, False,  True, False,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True],
       [ True, False,  True, False, False, False,  True, False, False,
        False,  True, False, False, False, False, False, False, False,
        False, False,  True, False,  True, False, False, False,  True,
        False,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True, False,  True,  True,  True,  True,  True,
        False,  True, False,  True],
       [ True, False,  True, False, False, False,  True, False, False,
        False,  True, False,  True, False, False, False,  True, False,
         True, False, False, False, False, False, False, False,  True,
        False,  True, False,  True],
       [ True, False,  True, False,  True, False,  True,  True,  True,
        False,  True, False,  True,  True,  True, False,  True, False,
         True, False,  True, False,  True,  True,  True, False,  True,
        False,  True,  True,  True],
       [ True, False, False, False,  True, False, False, False,  True,
        False,  True, False, False, False,  True, False,  True, False,
        False, False,  True, False, False, False,  True, False, False,
        False, False, False,  True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True,
        False,  True, False,  True, False,  True, False,  True,  True,
         True,  True,  True, False,  True, False,  True,  True,  True,
         True,  True, False,  True],
       [ True, False, False, False,  True, False, False, False,  True,
        False, False, False,  True, False,  True, False,  True, False,
        False, False,  True, False,  True, False, False, False,  True,
        False,  True, False,  True],
       [ True,  True,  True, False,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True, False,  True, False,  True,  True,  True,  True,  True,
        False,  True, False,  True],
       [ True, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False,  True, False,
        False, False, False, False,  True, False, False, False, False,
        False, False, False,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True]]

    maze5 = [[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True, False,  True, False, False, False, False, False,  True,
        False,  True, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False,
        False,  True, False,  True],
       [ True, False,  True, False,  True, False,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True, False,  True],
       [ True, False, False, False,  True, False,  True, False,  True,
        False, False, False,  True, False,  True, False,  True, False,
         True, False,  True, False, False, False,  True, False, False,
        False,  True, False,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True, False,  True, False,  True,  True,  True, False,
         True, False,  True,  True,  True,  True,  True, False,  True,
        False,  True, False,  True],
       [ True, False,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False,
        False, False,  True, False, False, False, False, False,  True,
        False,  True, False,  True],
       [ True, False,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True, False,  True, False,  True, False,  True,  True,  True,
         True,  True, False,  True],
       [ True, False, False, False,  True, False,  True, False, False,
        False, False, False,  True, False,  True, False, False, False,
         True, False, False, False,  True, False, False, False, False,
        False,  True, False,  True],
       [ True, False,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True, False,  True, False,  True,  True,
         True, False,  True,  True,  True,  True,  True, False,  True,
        False,  True, False,  True],
       [ True, False, False, False,  True, False,  True, False, False,
        False, False, False,  True, False, False, False,  True, False,
        False, False,  True, False, False, False, False, False,  True,
        False, False, False,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True,  True,
         True, False,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True],
       [ True, False, False, False, False, False, False, False, False,
        False, False, False,  True, False,  True, False,  True, False,
        False, False,  True, False, False, False, False, False, False,
        False, False, False,  True],
       [ True,  True,  True, False,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True, False, False, False,  True, False, False, False, False,
        False,  True, False,  True, False,  True, False,  True, False,
         True, False, False, False,  True, False,  True, False, False,
        False, False, False,  True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True, False,  True, False,  True, False,  True, False,
         True, False,  True,  True,  True, False,  True, False,  True,
         True,  True, False,  True],
       [ True, False,  True, False,  True, False, False, False,  True,
        False, False, False, False, False,  True, False, False, False,
        False, False,  True, False, False, False, False, False,  True,
        False, False, False,  True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True, False,  True, False,  True, False,
         True, False,  True,  True,  True, False,  True,  True,  True,
        False,  True, False,  True],
       [ True, False, False, False,  True, False,  True, False, False,
        False,  True, False,  True, False,  True, False,  True, False,
         True, False, False, False,  True, False,  True, False, False,
        False,  True, False,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True, False,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True],
       [ True, False, False, False, False, False,  True, False,  True,
        False,  True, False, False, False,  True, False, False, False,
         True, False, False, False, False, False, False, False,  True,
        False,  True, False,  True],
       [ True,  True,  True, False,  True,  True,  True, False,  True,
        False,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True, False,  True,  True,  True,
         True,  True, False,  True],
       [ True, False, False, False, False, False, False, False,  True,
        False, False, False, False, False,  True, False, False, False,
         True, False, False, False,  True, False, False, False,  True,
        False,  True, False,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True, False,  True, False,  True,
        False,  True, False,  True],
       [ True, False, False, False, False, False,  True, False, False,
        False, False, False, False, False, False, False,  True, False,
         True, False,  True, False,  True, False,  True, False, False,
        False, False, False,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True,
         True, False,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True, False,  True, False, False, False,  True, False,  True,
        False, False, False,  True, False, False, False,  True, False,
        False, False,  True, False,  True, False, False, False,  True,
        False, False, False,  True],
       [ True, False,  True,  True,  True, False,  True, False,  True,
        False,  True, False,  True,  True,  True, False,  True,  True,
         True, False,  True, False,  True, False,  True, False,  True,
        False,  True,  True,  True],
       [ True, False, False, False, False, False,  True, False, False,
        False,  True, False, False, False,  True, False, False, False,
        False, False,  True, False,  True, False,  True, False, False,
        False,  True, False,  True],
       [ True, False,  True,  True,  True, False,  True, False,  True,
        False,  True, False,  True,  True,  True,  True,  True, False,
         True,  True,  True, False,  True, False,  True,  True,  True,
        False,  True, False,  True],
       [ True, False,  True, False, False, False,  True, False,  True,
        False,  True, False, False, False, False, False,  True, False,
        False, False, False, False, False, False, False, False,  True,
        False, False, False,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True]]

    num = randrange(1, 6)
    if num == 1:
        return 31, 31, maze1
    elif num == 2:
        return 31, 31, maze2
    elif num == 3:
        return 31, 31, maze3
    elif num == 4:
        return 31, 31, maze4
    elif num == 5:
        return 31, 31, maze5